pipeline {
    agent any

    options {
        timeout(time: 1, unit: 'HOURS')
    }

    stages {
        stage('Build & Tag Image') {
            steps {
		sh '''mvn test'''
            }
        }
        

        stage('Pulling and Deploying') {
           steps {
               sh '''ls'''
           }
        }
    }
    post {
        always {
       		 cucumber buildStatus: 'UNSTABLE',
               		failedFeaturesNumber: 1,
               		failedScenariosNumber: 1,
               		skippedStepsNumber: 1,
             		failedStepsNumber: 1,
                	reportTitle: 'My report',
                	fileIncludePattern: '**/*cucumber.json',
                	sortingMethod: 'ALPHABETICAL',
                	trendsLimit: 100
   		}
   	 }
}
